
var app = angular.module("COLT", ["colt.directives"]);

app.run(function($rootScope, $http) {
	$http.get('autogenerated.colt',
		{transformResponse:function(data) {
			var x2js = new X2JS();
			var json = x2js.xml_str2json( data );
			return json;
		}
	})
	.then(function(res) {
		var model = $rootScope.model = res.data.xml;
		console.log(model);
	});
});

app.controller("SettingsCtrl", function($scope) {
	
	
});